### ISSUE TITLE
nydus-snapshotter + dragonfly  Multiple registry backend warehouses are supported

### ISSUE THREAD

**Issue by zhangzhuo0705** [containerd/nydus-snapshotter#634]
nydus-snapshotter config
```yaml
{
  "device": {
    "backend": {
      "type": "registry",
      "config": {
        "mirrors": [
          {
            "host": "http://127.0.0.1:4001",
            "auth_through": false,
            "headers": {
              "X-Dragonfly-Registry": "https://harbor-test.zhangzhuo.com"
            },
            "ping_url": "http://127.0.0.1:4003/healthy"
          }
        ],
        "scheme": "https",
        "skip_verify": true,
        "timeout": 10,
        "connect_timeout": 10,
        "retry_limit": 2
      }
    },
    "cache": {
      "type": "blobcache",
      "config": {
        "work_dir": "cache"
      }
    }
  },
  "mode": "direct",
  "digest_validate": false,
  "iostats_files": false,
  "enable_xattr": true,
  "fs_prefetch": {
    "enable": true,
    "threads_count": 10,
    "merging_size": 131072,
    "bandwidth_rate": 1048576
  }
}
```
The component works properly when pulling the harbor-test.zhangzhuo.com warehouse image，If pulling other additional image warehouse image dragonfly failed to work。
```bash
root@ceshi-2-15:/etc/containerd-nydus# cat /var/lib/containerd/io.containerd.snapshotter.v1.nydus/config/culefpqtr0s54ut3ou4g/config.json | jq
{
  "device": {
    "backend": {
      "type": "registry",
      "config": {
        "readahead": false,
        "host": "harbor.zhangzhuo.com",
        "repo": "library/nginx",
        "mirrors": [
          {
            "host": "http://127.0.0.1:4001",
            "headers": {
              "X-Dragonfly-Registry": "https://harbor-test.zhangzhuo.com"
            },
            "ping_url": "http://127.0.0.1:4003/healthy"
          }
        ],
        "scheme": "https",
        "skip_verify": true,
        "proxy": {
          "fallback": false
        },
        "timeout": 10,
        "connect_timeout": 10,
        "retry_limit": 2
      }
    },
    "cache": {
      "type": "blobcache",
      "config": {
        "work_dir": "/var/lib/containerd/io.containerd.snapshotter.v1.nydus/cache",
        "disable_indexed_map": false
      }
    }
  },
  "mode": "direct",
  "digest_validate": false,
  "enable_xattr": true,
  "fs_prefetch": {
    "enable": true,
    "prefetch_all": false,
    "threads_count": 10,
    "merging_size": 131072,
    "bandwidth_rate": 1048576
  }
}
```
